# Generated by Django 4.1.7 on 2023-04-23 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=8, unique=True)),
                ("game_mode", models.BooleanField(default=False)),
                ("player1", models.CharField(default="", max_length=50)),
                ("player2", models.CharField(default="", max_length=50)),
                ("player3", models.CharField(default="", max_length=50)),
                ("player4", models.CharField(default="", max_length=50)),
                ("current_player", models.CharField(default="", max_length=50)),
                ("zhuangjia", models.CharField(default="", max_length=50)),
                ("bamboo1", models.SmallIntegerField(default=4)),
                ("bamboo2", models.SmallIntegerField(default=4)),
                ("bamboo3", models.SmallIntegerField(default=4)),
                ("bamboo4", models.SmallIntegerField(default=4)),
                ("bamboo5", models.SmallIntegerField(default=4)),
                ("bamboo6", models.SmallIntegerField(default=4)),
                ("bamboo7", models.SmallIntegerField(default=4)),
                ("bamboo8", models.SmallIntegerField(default=4)),
                ("bamboo9", models.SmallIntegerField(default=4)),
                ("wan1", models.SmallIntegerField(default=4)),
                ("wan2", models.SmallIntegerField(default=4)),
                ("wan3", models.SmallIntegerField(default=4)),
                ("wan4", models.SmallIntegerField(default=4)),
                ("wan5", models.SmallIntegerField(default=4)),
                ("wan6", models.SmallIntegerField(default=4)),
                ("wan7", models.SmallIntegerField(default=4)),
                ("wan8", models.SmallIntegerField(default=4)),
                ("wan9", models.SmallIntegerField(default=4)),
                ("circle1", models.SmallIntegerField(default=4)),
                ("circle2", models.SmallIntegerField(default=4)),
                ("circle3", models.SmallIntegerField(default=4)),
                ("circle4", models.SmallIntegerField(default=4)),
                ("circle5", models.SmallIntegerField(default=4)),
                ("circle6", models.SmallIntegerField(default=4)),
                ("circle7", models.SmallIntegerField(default=4)),
                ("circle8", models.SmallIntegerField(default=4)),
                ("circle9", models.SmallIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=50, unique=True)),
                ("bamboo1", models.SmallIntegerField(default=0)),
                ("bamboo2", models.SmallIntegerField(default=0)),
                ("bamboo3", models.SmallIntegerField(default=0)),
                ("bamboo4", models.SmallIntegerField(default=0)),
                ("bamboo5", models.SmallIntegerField(default=0)),
                ("bamboo6", models.SmallIntegerField(default=0)),
                ("bamboo7", models.SmallIntegerField(default=0)),
                ("bamboo8", models.SmallIntegerField(default=0)),
                ("bamboo9", models.SmallIntegerField(default=0)),
                ("wan1", models.SmallIntegerField(default=0)),
                ("wan2", models.SmallIntegerField(default=0)),
                ("wan3", models.SmallIntegerField(default=0)),
                ("wan4", models.SmallIntegerField(default=0)),
                ("wan5", models.SmallIntegerField(default=0)),
                ("wan6", models.SmallIntegerField(default=0)),
                ("wan7", models.SmallIntegerField(default=0)),
                ("wan8", models.SmallIntegerField(default=0)),
                ("wan9", models.SmallIntegerField(default=0)),
                ("circle1", models.SmallIntegerField(default=0)),
                ("circle2", models.SmallIntegerField(default=0)),
                ("circle3", models.SmallIntegerField(default=0)),
                ("circle4", models.SmallIntegerField(default=0)),
                ("circle5", models.SmallIntegerField(default=0)),
                ("circle6", models.SmallIntegerField(default=0)),
                ("circle7", models.SmallIntegerField(default=0)),
                ("circle8", models.SmallIntegerField(default=0)),
                ("circle9", models.SmallIntegerField(default=0)),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_set",
                        to="App.room",
                    ),
                ),
            ],
        ),
    ]
