# Generated by Django 4.1.7 on 2023-03-23 05:20

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host_id',
            field=models.CharField(default=App.models.generate_random_host_id, max_length=50, unique=True),
        ),
    ]
