# Generated by Django 4.1.7 on 2023-03-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='player_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='player_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='player_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='player_4',
            field=models.CharField(default='', max_length=50),
        ),
    ]
