# Generated by Django 4.1.7 on 2023-03-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_room_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='App.player')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.room')),
            ],
        ),
    ]
