# Generated by Django 4.1.7 on 2023-03-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_room_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player_4',
            field=models.BooleanField(default=False),
        ),
    ]
