# Generated by Django 4.1.7 on 2023-04-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_room_bamboo1_room_bamboo2_room_bamboo3_room_bamboo4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='player2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='player3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='player4',
            field=models.CharField(default='', max_length=50),
        ),
    ]
