# Generated by Django 4.1.7 on 2023-04-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_room_player1_room_player2_room_player3_room_player4'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_player',
            field=models.IntegerField(default=1),
        ),
    ]
