# Generated by Django 4.1.7 on 2023-04-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_room_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='zhuangjia',
            field=models.CharField(default=models.CharField(default='', max_length=50), max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_player',
            field=models.CharField(default=models.CharField(default='', max_length=50), max_length=50),
        ),
    ]
