# Generated by Django 4.1.7 on 2023-03-09 05:06
from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('App', 'Student')
    Student(name="Joe Silver", email="joe@email.com", document="22342342", phone="00000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]